#!/bin/bash

echo "🧪 Test composant input_images"
echo "==============================="
echo ""
echo "📋 Étapes à tester:"
echo "1. Aller sur l'interface WorkflowRunner" 
echo "2. Ajouter une tâche 'Upload d'images' (input_images)"
echo "3. Vérifier que le composant s'affiche"
echo "4. Vérifier que le fallback q-file fonctionne"
echo ""
echo "🔍 Si le composant ne s'affiche toujours pas:"
echo "- Vérifier la console pour des erreurs"
echo "- Vérifier que task.type === 'input_images' est bien détecté"
echo "- Vérifier les imports de MediaSelector"
echo ""
echo "💡 Pour activer le MediaSelector:"
echo "- Changer 'v-if=\"false\"' en 'v-if=\"true\"' ligne ~305"